# local

db:
  host: db
  user: postgres
  password: password
  dbName: Music
  port: "5432"
sns:
  serverEndpoint: "http://localstack:4566"
  albumUpdateTopicArn: "arn:aws:sns:us-east-1:000000000000:album-update-events"
  region: "us-east-1"
  credentials:
    id: AKID
    secret: SECRET_KEY
    token: TOKEN
sqs:
  serverEndpoint: "http://localstack:4566"
  region: "us-east-1"
  credentials:
    id: AKID
    secret: SECRET_KEY
    token: TOKEN
  